# Generated by Django 4.0.6 on 2022-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_book_language_bookcopy_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
