# Generated by Django 4.0.6 on 2022-07-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_category_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='isbn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category'),
        ),
    ]
