# Generated by Django 4.0.6 on 2022-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookcopy_isbn_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
