# Generated by Django 4.0.6 on 2022-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookcopy_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='translator',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='translator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
