# Generated by Django 4.0.6 on 2022-07-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_shelf_category_num_category_sign_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_shelf',
        ),
    ]
