# Generated by Django 4.0.6 on 2022-07-29 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_delete_book_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='num',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='sign',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
