# Generated by Django 4.0.6 on 2022-08-03 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_category_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-create_on']},
        ),
        migrations.AddField(
            model_name='category',
            name='create_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
