# Generated by Django 4.0.6 on 2022-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_category_options_category_create_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
